import type { DemoDataState } from "@/app/lib/demo/types";

export const DEMO_SEED: DemoDataState = {
  settings: {
    email: "radijumi@utility.lv",
    emailPassword: "demo-parole",
    smsNumber: "+371 2000 0001",
    whatsappNumber: "+371 2000 0002",
    phoneNumber: "+371 6700 0000",
  },
  clients: [
    {
      id: "client-1",
      clientNumber: "12345",
      address: "Brīvības iela 1, Rīga",
      meterIds: ["meter-1", "meter-2", "meter-3", "meter-4", "meter-5"],
    },
    {
      id: "client-2",
      clientNumber: "67890",
      address: "Tallinas iela 5, Rīga",
      meterIds: ["meter-6", "meter-7", "meter-8"],
    },
    {
      id: "client-3",
      clientNumber: "11111",
      address: "Elizabetes iela 10, Rīga",
      meterIds: ["meter-9", "meter-10", "meter-11", "meter-12"],
    },
  ],
  meters: [
    {
      id: "meter-1",
      number: "HW-1001",
      type: "hot_water",
      verificationDate: "2025-03-15",
      clientId: "client-1",
      location: "Virtuve",
      previousReading: 120.5,
    },
    {
      id: "meter-2",
      number: "HW-1002",
      type: "hot_water",
      verificationDate: "2025-03-15",
      clientId: "client-1",
      location: "Vannas istaba",
      previousReading: 89.2,
    },
    {
      id: "meter-3",
      number: "CW-2001",
      type: "cold_water",
      verificationDate: "2024-11-20",
      clientId: "client-1",
      location: "Virtuve",
      previousReading: 45,
    },
    {
      id: "meter-4",
      number: "CW-2002",
      type: "cold_water",
      verificationDate: "2024-11-20",
      clientId: "client-1",
      location: "Vannas istaba",
      previousReading: 32.1,
    },
    {
      id: "meter-5",
      number: "SW-3001",
      type: "sewage",
      verificationDate: "2025-01-10",
      clientId: "client-1",
      location: "Kopējā",
      previousReading: 77,
    },
    {
      id: "meter-6",
      number: "HW-2001",
      type: "hot_water",
      verificationDate: "2025-06-01",
      clientId: "client-2",
      location: "Virtuve",
      previousReading: 210.4,
    },
    {
      id: "meter-7",
      number: "CW-3001",
      type: "cold_water",
      verificationDate: "2025-06-01",
      clientId: "client-2",
      location: "Virtuve",
      previousReading: 88.7,
    },
    {
      id: "meter-8",
      number: "SW-4001",
      type: "sewage",
      verificationDate: "2025-06-01",
      clientId: "client-2",
      location: "Kopējā",
      previousReading: 150.2,
    },
    {
      id: "meter-9",
      number: "HW-3001",
      type: "hot_water",
      verificationDate: "2024-09-12",
      clientId: "client-3",
      location: "Virtuve",
      previousReading: 55.3,
    },
    {
      id: "meter-10",
      number: "CW-4001",
      type: "cold_water",
      verificationDate: "2024-09-12",
      clientId: "client-3",
      location: "Virtuve",
      previousReading: 22.8,
    },
    {
      id: "meter-11",
      number: "CW-4002",
      type: "cold_water",
      verificationDate: "2024-09-12",
      clientId: "client-3",
      location: "Sanmezgls",
      previousReading: 11.5,
    },
    {
      id: "meter-12",
      number: "SW-5001",
      type: "sewage",
      verificationDate: "2024-09-12",
      clientId: "client-3",
      location: "Kopējā",
      previousReading: 34.6,
    },
  ],
  submissions: [
    {
      clientId: "client-3",
      month: "2026-05",
      submittedAt: "2026-05-28T10:15:00.000Z",
      readings: {
        "meter-9": 58.1,
        "meter-10": 24.2,
        "meter-11": 12.4,
        "meter-12": 36.9,
      },
    },
  ],
};
